### ISSUE TITLE
Profile Picture Viewer No Longer Works on Instagram

### ISSUE THREAD

**Issue by joevan8484** [Ademking/profile-picture-viewer#12]
There sees to be an update on Instagram that allows images to be viewed in a separate app natively on the web app. This extension no longer works on it.

**Comment by Ademking** [comment]
Hello @joevan8484 
I'm aware of this issue and I will update the extension very soon!
Thank you for your feedback! 👍

**Comment by Ademking** [comment]
@joevan8484 The problem has been fixed. It's working now (version 1.0.8)
Chrome Web Store takes time to update the extension.
